import type { Approval, ApprovalTemplate } from "./types";
// Synthetic requests shared by API key history and approval views.
export const approvals: Approval[] = [
  {
    id: "approval-001",
    keyId: "key-directory",
    type: "issue",
    templateId: "template-key-issue-v1",
    status: "approved",
    requesterId: "usr-001",
    reviewerId: "usr-006",
    requestedAt: "2026-07-01T00:00:00Z",
    decidedAt: "2026-07-01T01:00:00Z",
    reason: "구성원 동기화 연동 시작",
    comment: "사용 목적 확인",
  },
  {
    id: "approval-002",
    keyId: "key-directory",
    type: "renew",
    templateId: "template-key-renew-v1",
    status: "rejected",
    requesterId: "usr-001",
    reviewerId: "usr-006",
    requestedAt: "2026-07-10T00:00:00Z",
    decidedAt: "2026-07-10T01:00:00Z",
    reason: "사용 기간 연장",
    comment: "필요 기간을 구체적으로 작성해 주세요.",
  },
  {
    id: "approval-003",
    keyId: "key-directory",
    type: "renew",
    templateId: "template-key-renew-v1",
    status: "approved",
    requesterId: "usr-001",
    reviewerId: "usr-006",
    requestedAt: "2026-07-11T00:00:00Z",
    decidedAt: "2026-07-11T01:00:00Z",
    reason: "분기 동기화 작업을 위한 연장",
    comment: "일정 확인",
  },
  {
    id: "approval-004",
    keyId: "key-directory",
    type: "renew",
    templateId: "template-key-renew-v1",
    status: "approved",
    requesterId: "usr-001",
    reviewerId: "usr-007",
    requestedAt: "2026-08-01T00:00:00Z",
    decidedAt: "2026-08-01T01:00:00Z",
    reason: "하반기 동기화 운영",
    comment: "운영 계획 확인",
  },
  {
    id: "approval-005",
    keyId: "key-directory",
    type: "revoke",
    templateId: "template-key-revoke-v1",
    status: "rejected",
    requesterId: "usr-001",
    reviewerId: "usr-006",
    requestedAt: "2026-09-01T00:00:00Z",
    decidedAt: "2026-09-01T01:00:00Z",
    reason: "신규 연동으로 전환",
    comment: "전환 완료 후 다시 요청해 주세요.",
  },
  {
    id: "approval-006",
    keyId: "key-directory",
    type: "revoke",
    templateId: "template-key-revoke-v1",
    status: "pending",
    requesterId: "usr-001",
    reviewerId: null,
    requestedAt: "2026-09-23T03:00:00Z",
    decidedAt: null,
    reason: "동기화 연동 전환 완료에 따른 폐기 요청",
    comment: null,
  },
  {
    id: "approval-007",
    keyId: "key-platform-ci",
    type: "issue",
    templateId: "template-key-issue-v1",
    status: "approved",
    requesterId: "usr-002",
    reviewerId: "usr-006",
    requestedAt: "2026-08-01T00:00:00Z",
    decidedAt: "2026-08-01T01:00:00Z",
    reason: "파이프라인 연동",
    comment: "사용 목적 확인",
  },
];
export const templates: ApprovalTemplate[] = [
  {
    id: "template-key-issue-v1",
    name: "API 키 발급",
    description: "신규 API 키 발급 요청용 예제 템플릿",
    type: "issue",
    version: 1,
    status: "active",
    instructions: "사용 목적, 소속 조직과 필요한 사용 기간을 작성합니다.",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "template-key-renew-v1",
    name: "API 키 갱신",
    description: "API 키 사용 기간 연장 요청용 예제 템플릿",
    type: "renew",
    version: 1,
    status: "active",
    instructions: "갱신 대상 키와 연장 기간, 사유를 작성합니다.",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "template-key-revoke-v1",
    name: "API 키 폐기",
    description: "API 키 사용 종료 요청용 예제 템플릿",
    type: "revoke",
    version: 1,
    status: "active",
    instructions: "폐기 사유와 연동 전환 여부를 작성합니다.",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "template-key-legacy-v1",
    name: "이전 API 키 발급",
    description: "사용 중지된 예제 템플릿",
    type: "issue",
    version: 1,
    status: "inactive",
    instructions: "현재 사용하지 않는 예제 양식입니다.",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
];
