apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - importer-job.yaml
configMapGenerator:
  - name: orion-resource-candidate
    files:
      - resources.yaml
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
