export const files: Record<string, string> = {
  "organizations.yaml":
    "organization:\n  id: sales\n  name: 영업본부\n---\norganization:\n  id: sales-team-1\n  name: 영업1팀\n  parent: sales\n---\norganization:\n  id: identity-team\n  name: Identity 관리팀\n\n---\norganization:\n  id: org-platform\n  name: 플랫폼개발팀\n",
  "masking-rules.yaml":
    'masking-rules:\n  email:\n    description: 이메일 아이디 첫 글자와 도메인 표시\n    method: email\n    local-part: { keep-start: 1, keep-end: 0 }\n    domain: preserve\n    replacement: "*"\n    replacement-length: 3\n    on-short: redact\n    on-invalid: redact\n  name:\n    description: 첫 글자만 표시\n    method: partial\n    keep-start: 1\n    keep-end: 0\n    replacement: "*"\n    replacement-length: 2\n    on-short: redact\n  redact:\n    description: 전체 값 대체\n    method: redact\n    replacement: "[REDACTED]"\n',
  "domains/employee.yaml":
    "domain:\n  id: employee\n  name: 직원 관리\n  scopes:\n    sales-region:\n      name: 영업 지역\n      codes:\n        - { code: SEOUL, name: 서울 }\n        - { code: GYEONGGI, name: 경기 }\n        - { code: BUSAN, name: 부산 }\n      organizations:\n        - organization: sales-team-1\n          codes: [SEOUL, BUSAN]\n        - organization: org-platform\n          codes: [SEOUL]\n  actions:\n    read-regional-employees:\n      name: 담당 지역 직원 조회\n      endpoint:\n        service: employee-api\n        endpoint: search\n        request:\n          fields:\n            - keyword\n            - region_codes: { scope: sales-region }\n            - requester_email: { source: subject.email }\n        response:\n          fields:\n            - employee_name\n            - email_address\n            - region_code\n    read-regional-contacts:\n      name: 담당 지역 연락처 원문 조회\n      endpoint:\n        service: employee-api\n        endpoint: search\n        request:\n          fields:\n            - keyword\n            - region_codes: { scope: sales-region }\n            - requester_email: { source: subject.email }\n        response:\n          fields:\n            - employee_name: { unmask: true }\n            - email_address: { unmask: true }\n            - region_code\n    read-service-employees:\n      name: 서비스 직원 조회\n      endpoint:\n        service: employee-api\n        endpoint: search\n        request:\n          fields:\n            - keyword\n            - region_codes: { scope: sales-region }\n        response:\n          fields:\n            - employee_name\n            - region_code\n",
  "platforms/sales-platform/workspaces/sales-console.yaml":
    "workspace:\n  id: sales-console\n  platform: sales-platform\n  name: 영업 관리\n  pages:\n    - id: regional-employees\n      name: 담당 지역 직원\n      path: /employees/regional\n      actions:\n        - { domain: employee, action: read-regional-employees }\n        - { domain: employee, action: read-regional-contacts }\n",
  "services/identity-team/employee-api/service.yaml":
    "service:\n  id: employee-api\n  name: 직원 API\n  organization: identity-team\n",
  "services/identity-team/employee-api/endpoints/health.yaml":
    "service: employee-api\nendpoints:\n  - id: health\n    name: 서비스 상태 조회\n    method: GET\n    path: /health\n    request: { fields: {} }\n    response:\n      fields:\n        status: { path: /status, type: string, privacy: false }\n",
  "services/identity-team/employee-api/endpoints/employees.yaml":
    "service: employee-api\nendpoints:\n  - id: search\n    name: 직원 검색\n    method: POST\n    path: /employees/search\n    request:\n      fields:\n        keyword:\n          { location: body, path: /keyword, type: string, privacy: false }\n        region_codes:\n          location: body\n          path: /filter/region_codes\n          type: array\n          items: { type: string }\n          required: true\n          privacy: false\n        requester_email:\n          location: body\n          path: /requester_email\n          type: string\n          required: false\n          privacy: true\n          masking: email\n        internal_option:\n          {\n            location: body,\n            path: /internal_option,\n            type: boolean,\n            privacy: false,\n          }\n    response:\n      fields:\n        employee_name:\n          {\n            path: /items/*/employee_name,\n            type: string,\n            privacy: true,\n            masking: name,\n          }\n        email_address:\n          {\n            path: /items/*/email_address,\n            type: string,\n            privacy: true,\n            masking: email,\n          }\n        region_code:\n          { path: /items/*/region_code, type: string, privacy: false }\n        internal_note:\n          {\n            path: /items/*/internal_note,\n            type: string,\n            privacy: true,\n            masking: redact,\n          }\n",
  "policies/employee.yaml":
    "policies:\n  regional-reader:\n    name: 직원 기본 조회\n    assignable_to: role\n    effect: allow\n    workspaces:\n      sales-platform.sales-console:\n        pages:\n          regional-employees:\n            actions: [employee.read-regional-employees]\n  regional-contact-reader:\n    name: 직원 연락처 조회\n    assignable_to: role\n    effect: allow\n    workspaces:\n      sales-platform.sales-console:\n        pages:\n          regional-employees:\n            actions: [employee.read-regional-contacts]\n  regional-reader-backup:\n    name: 직원 기본 조회 · 공통 업무\n    assignable_to: role\n    effect: allow\n    workspaces:\n      sales-platform.sales-console:\n        pages:\n          regional-employees:\n            actions: [employee.read-regional-employees]\n  deny-regional-contacts:\n    name: 직원 연락처 조회 제한\n    assignable_to: role\n    effect: deny\n    workspaces:\n      sales-platform.sales-console:\n        pages:\n          regional-employees:\n            actions: [employee.read-regional-contacts]\n  service-employee-reader:\n    name: 서비스 직원 조회\n    assignable_to: service_account\n    effect: allow\n    actions: [employee.read-service-employees]\n  service-contact-reader:\n    name: 서비스 연락처 조회 · 사용자 속성 필요\n    assignable_to: service_account\n    effect: allow\n    actions: [employee.read-regional-contacts]\n",
  "platforms/sales-platform/platform.yaml":
    "platforms:\n  sales-platform:\n    name: 영업 플랫폼\n",
};
