# Deployment template: replace repository, destination and project before applying.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orion-resources-development-ap-northeast-2
  namespace: argocd
spec:
  project: orion
  source:
    repoURL: https://github.com/minjoonchoi/orion.git
    targetRevision: master
    path: deploy/resource-catalog
  destination:
    server: https://kubernetes.default.svc
    namespace: orion
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
